MODULE ELEMENT_CLASS

	TYPE ELEMENT
	INTEGER, DIMENSION(4) :: nodeids
	INTEGER, DIMENSION(4) :: nbrelemids
	CHARACTER(LEN=72), DIMENSION(4) :: bcnames
	REAL(8), DIMENSION(4,2) :: normals
	REAL(8), DIMENSION(4) :: length
	REAL(8)				:: volume 
	END TYPE ELEMENT

END MODULE ELEMENT_CLASS