	PROGRAM TEST
		USE VARS

		IMPLICIT NONE

		INTEGER :: i
		TYPE(ARRAYS), DIMENSION(:), ALLOCATABLE :: GRID 

			ALLOCATE (GRID(2))
			DO i = 1,2 
				ALLOCATE(GRID(i)%U(3,3),GRID(i)%F(3,3))
			ENDDO
		END PROGRAM
